# Generated by Django 5.1.5 on 2025-02-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='libro',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='libro',
            name='anio_publicacion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
